# Docker Compose file for pyrobosim
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To run a specific service by name:
#   docker compose run <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:
  base:
    image: pyrobosim:${ROS_DISTRO:-humble}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-humble}
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Allows graphical programs in the container.
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    # Mount the source code
      - ./pyrobosim/:/ros2_ws/src/pyrobosim/pyrobosim:rw
      - ./pyrobosim_msgs/:/ros2_ws/src/pyrobosim/pyrobosim_msgs/:rw
      - ./pyrobosim_ros/:/ros2_ws/src/pyrobosim/pyrobosim_ros/:rw
      - ./test/:/ros2_ws/src/pyrobosim/test/:rw
      - ./pytest.ini:/ros2_ws/src/pyrobosim/pytest.ini:rw
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command: /bin/bash

  test:
    extends: base
    command: test/run_tests.bash ${ROS_DISTRO:-humble}

  ###############
  # Basic demos #
  ###############
  demo:
    extends: base
    command: python3 src/pyrobosim/examples/demo.py
  demo_multirobot:
    extends: base
    command: python3 src/pyrobosim/examples/demo.py --multirobot
  demo_ros:
    extends: base
    command: ros2 launch pyrobosim_ros demo.launch.py
  task_allocation_ros:
    extends: base
    command: ros2 launch pyrobosim_ros task_allocation.launch.py  
  demo_multirobot_ros:
    extends: base
    command: ros2 launch pyrobosim_ros demo_commands_multirobot.launch.py

  ##################################
  # Task and Motion Planning demos #
  ##################################
  demo_pddl:
    extends: base
    command: python3 src/pyrobosim/examples/demo_pddl.py --example 01_simple --verbose
  demo_pddl_ros:
    extends: base
    command: ros2 launch pyrobosim_ros demo_pddl.launch.py example:=01_simple subscribe:=true verbose:=true
